cmake_minimum_required(VERSION 3.27.0)
project(UNITY LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(epoll_sever_run src/run_epoll_sever.cpp src/manager.cpp src/sever.cpp src/building_catalog.cpp)
add_executable(client_run src/run_client.cpp)
add_executable(catalog_lookup_run src/catalog_lookup.cpp src/building_catalog.cpp)
